-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.3

local tab = {
	Sample = {
		{ ID = 100, Name = "黑猫警长", EmptyName = "", IconID = 0, NumericalRate = 0.6, ItemID = 100, BuffID = { 10 }, Pos = { X= 100, Y= 89 }, Type = 0, SkillID = { 4, 6, 7 }, AttackParam = { Value= 1 }, SingleStruct = { HP= 100, AttackRate= 1.2 }, StrStruct = { { HP= 3, ExType= 0 }, { HP= 10, ExType= 1 } } 	},
		{ ID = 101, Name = "葫芦\n娃", EmptyName = "", IconID = 0, NumericalRate = 0.8, ItemID = 100, BuffID = { 3, 1 }, Pos = {  }, Type = 2, SkillID = { 1 }, AttackParam = {  }, SingleStruct = { HP= 10, AttackRate= 0, ExType= 0 }, StrStruct = { {  } } 	},
		{ ID = 102, Name = "舒\"克\"", EmptyName = "", IconID = 0, NumericalRate = 0.7, ItemID = 100, BuffID = {  }, Pos = {  }, Type = 3, SkillID = {  }, AttackParam = {  }, SingleStruct = { HP= 10, AttackRate= 0, ExType= 0 }, StrStruct = { {  } } 	},
		{ ID = 103, Name = "贝\n塔", EmptyName = "", IconID = 0, NumericalRate = 0, ItemID = 100, BuffID = {  }, Pos = {  }, Type = 1, SkillID = {  }, AttackParam = {  }, SingleStruct = { HP= 10, AttackRate= 0, ExType= 0 }, StrStruct = { {  } } 	},
		{ ID = 104, Name = "邋遢大王", EmptyName = "", IconID = 0, NumericalRate = 1, ItemID = 100, BuffID = {  }, Pos = {  }, Type = 2, SkillID = {  }, AttackParam = {  }, SingleStruct = { HP= 10, AttackRate= 0, ExType= 0 }, StrStruct = { {  } } 	}
	}, 

	Example = {
		{ ID = 1000, Name = "aaaaa", FullName = "", Desc = "" 	},
		{ ID = 1001, Name = "bbbb", FullName = "", Desc = "" 	}
	}, 

	Item = {
		{ ItemID = 1111, ItemName = "装备", IconID = 0 	},
		{ ItemID = 1112, ItemName = "道具", IconID = 0 	},
		{ ItemID = 1113, ItemName = "剑", IconID = 0 	},
		{ ItemID = 1114, ItemName = "武器", IconID = 0 	}
	}

}


-- ID
tab.SampleByID = {}
for _, rec in pairs(tab.Sample) do
	tab.SampleByID[rec.ID] = rec
end

-- Name
tab.SampleByName = {}
for _, rec in pairs(tab.Sample) do
	tab.SampleByName[rec.Name] = rec
end

-- ID
tab.ExampleByID = {}
for _, rec in pairs(tab.Example) do
	tab.ExampleByID[rec.ID] = rec
end

-- Name
tab.ExampleByName = {}
for _, rec in pairs(tab.Example) do
	tab.ExampleByName[rec.Name] = rec
end

-- ItemID
tab.ItemByItemID = {}
for _, rec in pairs(tab.Item) do
	tab.ItemByItemID[rec.ItemID] = rec
end

-- ItemName
tab.ItemByItemName = {}
for _, rec in pairs(tab.Item) do
	tab.ItemByItemName[rec.ItemName] = rec
end

tab.Enum = {
	ActorType = {
		[0] = "Leader",
		[2] = "Pig",
		Monkey = 1,
		Hammer = 3,
	},
}

return tab